<?php require_once __DIR__ . '/includes/functions.php'; require_once __DIR__ . '/includes/config.php'; $token = csrf_token(); ?>
<!doctype html>
<html lang="en" class="scroll-smooth">
<head>
  <meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Naran Tour Package | Modern Ways Tours</title>
  <meta name="description" content="Premium Naran Tour Package by Modern Ways Tours with 19 sightseeing points, hotel, meals, jeeps, activities and full tour support.">
  <link rel="icon" href="assets/images/favicon.png"><script src="https://cdn.tailwindcss.com"></script>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.2/css/all.min.css"><link rel="stylesheet" href="assets/css/style.css">
  <script>tailwind.config={theme:{extend:{colors:{navy:'#071b3a',gold:'#d6a84f',cream:'#fff8ec'}}}}</script>
</head>
<body class="bg-slate-50 text-slate-800">
<header class="fixed inset-x-0 top-0 z-40 border-b border-white/10 bg-navy/90 backdrop-blur-xl">
  <nav class="mx-auto flex max-w-7xl items-center justify-between px-4 py-3"><a href="#home" class="flex items-center gap-3"><img src="assets/images/header.png" onerror="this.src='assets/images/logo.png'" class="h-12 w-auto animate-float" alt="Modern Ways Tours"><span class="font-bold text-white">Modern Ways Tours</span></a>
  <button id="menuBtn" class="text-2xl text-white md:hidden"><i class="fa-solid fa-bars"></i></button><div id="navMenu" class="hidden absolute left-0 right-0 top-full bg-navy p-5 md:static md:flex md:bg-transparent md:p-0 items-center gap-6 text-sm font-semibold text-white"><a href="#home">Home</a><a href="#package">Package</a><a href="#points">Points</a><a href="#services">Services</a><a href="#gallery">Gallery</a><a href="#contact">Contact</a><button data-open="bookingModal" class="rounded-full bg-gold px-5 py-2 text-navy shadow-lg">Book Now</button></div></nav>
</header>
<main id="home">
<section class="hero relative min-h-screen overflow-hidden bg-navy pt-28 text-white" style="background-image:linear-gradient(110deg,rgba(7,27,58,.88),rgba(7,27,58,.35)),url('assets/images/hero-naran.jpg')"><div class="mx-auto grid max-w-7xl gap-10 px-4 py-24 lg:grid-cols-2 lg:items-center"><div class="reveal"><p class="mb-4 inline-flex rounded-full border border-gold/50 bg-white/10 px-4 py-2 text-gold">Premium All-Inclusive Sightseeing Experience</p><h1 class="text-5xl font-black leading-tight md:text-7xl">Naran Tour Package</h1><p class="mt-5 text-xl text-slate-100">3 Days / 2 Nights Premium All-Inclusive Sightseeing Experience</p><div class="mt-8 grid gap-3 sm:grid-cols-2"><span class="badge">19 Sightseeing Points</span><span class="badge">4-Star Accommodation</span><span class="badge">Private Couple Room</span><span class="badge">All Required Jeeps Included</span></div><div class="mt-10 flex flex-wrap gap-4"><button data-open="bookingModal" class="btn-gold">Book Your Place</button><a class="btn-light" href="https://wa.me/923355623281?text=I%20am%20interested%20in%20the%20Naran%20Tour%20Package" target="_blank">Contact Us on WhatsApp</a></div></div><div class="glass-card reveal"><img src="assets/images/logo.png" class="mx-auto h-28 animate-float" alt="Modern Ways Tours"><h2 class="mt-8 text-3xl font-bold">Luxury comfort, mountain adventure, and complete support.</h2><p class="mt-4 text-slate-200">From hotel check-in to jeep coordination, meals, activities, and tour management — everything listed is handled by our team.</p></div></div></section>
<section id="package" class="section"><div class="mx-auto max-w-7xl px-4"><h2 class="section-title">Clear Package Pricing</h2><div class="grid gap-6 md:grid-cols-2"><div class="price-card"><h3>Group / Normal Package</h3><p class="mt-4 text-slate-500 line-through">Original Price: PKR 29,000 per head</p><p class="mt-2 text-3xl font-black text-navy">After 10% Discount: PKR 26,000 per head only</p></div><div class="price-card"><h3>Couple Package</h3><p class="mt-4 text-3xl font-black text-navy">Couple Package: PKR 38,000 per head</p><p class="mt-2 text-slate-600">Private couple room included</p></div></div></div></section>
<section id="points" class="section bg-cream"><div class="mx-auto max-w-7xl px-4"><h2 class="section-title">Includes 19 Sightseeing Points</h2><div class="grid gap-4 md:grid-cols-2 lg:grid-cols-3"><?php $points=['Shatay Village','Kunhar View Point','Balakot','Jammu Da Nakka','Kiwai Waterfalls','Siri Lake & Paye Top','Shogran','Kaghan Bazaar & Suki Kinari Dam','Naran Bazaar & Kunhar Rafting Point','Lulusar Jheel','Babusar Top & Giti Das','Saif-ul-Malook Jheel & Saif-ul-Malook Caves','Batakundi & Jhalkhad / Tiger Peak View']; foreach($points as $i=>$p): ?><div class="tour-card"><span><?= $i+1 ?></span><?= e($p) ?></div><?php endforeach; ?></div></div></section>
<section id="services" class="section"><div class="mx-auto max-w-7xl px-4"><h2 class="section-title">Premium Services Included</h2><div class="grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><?php $services=['Premium AC + Heater Transport','Fuel, Tolls & Road Taxes Included','Premium Paid Motorway Toilet Facilities Both Ways','All Required Jeep Rides Included','4-Star Hotel Accommodation','Private Room for Couples','Group Rooms with Maximum 5–6 Persons','Daily Breakfast & Dinner','Horse Riding at Paye Top','Photo Shoot Included','Rafting / Zipline at Naran','Boating at Saif-ul-Malook','Mega Musical Bonfire at Shogran','Dedicated Tour Guide / Tour Manager','Hotel Check-in Support','Activity & Jeep Coordination','Basic First-Aid Support','Customer Support During Tour','Safety & Timing Management','Backup Planning for Weather & Road Issues']; foreach($services as $s): ?><div class="service-card"><i class="fa-solid fa-check text-gold"></i><span><?= e($s) ?></span></div><?php endforeach; ?></div></div></section>
<section class="bg-navy py-16 text-white"><div class="mx-auto max-w-5xl px-4 text-center text-xl leading-relaxed">You just enjoy the journey — we handle the rest. All listed sightseeing points, required jeep rides, hotel stay, meals, premium paid motorway toilet facilities, boating, rafting/zipline, horse riding, bonfire, guide support, and tour management are included. Customers only pay for personal shopping, extra personal food, room service, and personal expenses.</div></section>
<section id="gallery" class="section"><div class="mx-auto max-w-7xl px-4"><h2 class="section-title">Gallery</h2><div class="grid gap-6 md:grid-cols-4"><?php foreach(['kiwai.jpg'=>'Kiwai Waterfalls','saifulmalook.jpg'=>'Saif-ul-Malook','babusar.jpg'=>'Babusar Top','shogran.jpg'=>'Shogran'] as $img=>$cap): ?><figure class="gallery-card"><img src="assets/images/<?= e($img) ?>" alt="<?= e($cap) ?>"><figcaption><?= e($cap) ?></figcaption></figure><?php endforeach; ?></div></div></section>
<section class="section bg-cream"><div class="mx-auto max-w-7xl px-4"><h2 class="section-title">Why Choose Us</h2><div class="grid gap-5 md:grid-cols-3"><?php foreach(['19 Scenic Points','All-Inclusive Package','Private Couple Room','Premium Travel Management','Adventure Activities Included','No Stress, Full Support'] as $w): ?><div class="why-card"><i class="fa-solid fa-mountain-sun"></i><h3><?= e($w) ?></h3></div><?php endforeach; ?></div></div></section>
<section id="contact" class="section bg-navy text-white"><div class="mx-auto max-w-4xl px-4 text-center"><img src="assets/images/footer.png" onerror="this.src='assets/images/logo.png'" class="mx-auto mb-6 h-20" alt="Modern Ways Tours"><h2 class="text-4xl font-black">Start Your Naran Journey</h2><p class="mt-4">Phone/WhatsApp: +923355623281 • Website: tours.logaixa.com</p><div class="mt-8 flex justify-center gap-4"><button data-open="contactModal" class="btn-light">Contact Us</button><button data-open="bookingModal" class="btn-gold">Book Your Place</button></div></div></section>
</main>
<?php include __DIR__ . '/modal-forms.php'; ?>
<footer class="bg-slate-950 py-6 text-center text-white">© <?= date('Y') ?> Modern Ways Tours. All rights reserved.</footer><script src="assets/js/main.js"></script>
</body></html>
